import { reactive } from 'vue';
import { getFileSystem } from '../../api/FileSystem';
import { useAssetStore } from '../../stores/useAssetStore';
import { useUIStore } from '../../stores/useUIStore';

export const projectState = reactive({
    currentProjectPath: null as string | FileSystemDirectoryHandle | null,
    isDirty: false,
    projectName: 'Untitled',
    watcherCleanup: null as (() => void) | null
});

export class ProjectManager {
    
    static getRecents(): {name: string, path: string}[] {
        try {
            const stored = localStorage.getItem('ulikit_recents');
            return stored ? JSON.parse(stored) : [];
        } catch (e) {
            return [];
        }
    }

    static addToRecents(name: string, path?: string) {
        const recents = this.getRecents();
        // Remove existing if present to move to top
        const filtered = recents.filter(r => r.name !== name);
        const projectPath = path || name; // Use path if available (Electron), else name (Web)
        filtered.unshift({ name, path: projectPath }); 
        // Limit to 10
        if (filtered.length > 50) filtered.pop();
        
        localStorage.setItem('ulikit_recents', JSON.stringify(filtered));
    }

    static async createProject(customPath?: string) {
        const _pStart = performance.now();
        console.log('ProjectManager: Creating new project...', customPath ? `(Path: ${customPath})` : '(Interactive)');
        const fs = getFileSystem();
        const ui = useUIStore();
        
        // Use provided path or ask user
        const pathOrHandle = customPath || await fs.selectFolder();
        
        if (pathOrHandle) {
            // @ts-ignore
            if (ui.setLoading) ui.setLoading(true, 'Creating Project...'); 
            const result = await fs.createProject(pathOrHandle as any);
            
            if (result.success) {
                 projectState.currentProjectPath = pathOrHandle;
                 
                 let projectPathString = '';
                 if (typeof pathOrHandle === 'string') {
                    projectPathString = pathOrHandle;
                    projectState.projectName = pathOrHandle.replace(/[\\/]$/, '').split(/[/\\]/).pop() || 'New Project';
                 } else {
                    // Fallback for Handles? Assuming string for now based on current FS implementations
                    projectState.projectName = (pathOrHandle as FileSystemDirectoryHandle).name;
                    projectPathString = projectState.projectName; 
                 }

                 // [NEW] Use ProjectFactory to populate the empty folder
                 const { ProjectFactory } = await import('./ProjectFactory');
                 console.log(`[ProjectManager] Delegating initialization to ProjectFactory for path: ${projectPathString}`);
                 
                 const initialized = await ProjectFactory.initializeNewProject(projectPathString, projectState.projectName);
                 
                 if (!initialized) {
                     throw new Error('ProjectFactory failed to initialize project structure.');
                 }

                 // -------------------------------------------------------------------------
                 // Project Created & Verified on Disk. Now Open it in Editor Memory.
                 // -------------------------------------------------------------------------

                 // 1. Load Manifest (Should exist now)
                 const { ProjectManifestManager } = await import('./ProjectManifestManager');
                 const loaded = await ProjectManifestManager.loadProject('project.json');
                 
                 // [NEW] Sync Reactive Store
                 const { useProjectStore } = await import('../../stores/useProjectStore');
                 useProjectStore().sync();

                 if (!loaded) {
                     throw new Error('Critical: Project created but project.json cannot be read.');
                 }

                 // 2. Hydrate Asset Database
                 // 2. Hydrate Asset Database
                 // Already handled by loadProject
                 
                 // 3. Notify AssetStore
                 // @ts-ignore
                 await useAssetStore().refreshFromDatabase();
                 
                 // 4. Initialize Watcher
                 await this.initProjectWatcher(fs, projectState.currentProjectPath as any);

                 const _pEnd = performance.now();
                 console.log(`%c ⏱️ CREATION COMPLETE: ${(_pEnd - _pStart).toFixed(2)}ms `, 'background: #bada55; color: #222; font-size: 20px;');
                 
                 this.addToRecents(projectState.projectName, typeof pathOrHandle === 'string' ? pathOrHandle : undefined);

                 // 5. Load Initial Scene (Generated by Factory)
                 const { SceneManager } = await import('../../engine/managers/SceneManager');
                 const manifest = ProjectManifestManager.manifest;
                 
                 if (manifest && manifest.scenes && manifest.scenes.length > 0) {
                     const firstScene = manifest.scenes[0];
                     if (firstScene) await SceneManager.loadSceneByPath(firstScene.path);
                 } else {
                     console.warn('Factory created project but no scenes found in manifest?');
                     SceneManager.createDefaultScene();
                 }
                 
                 // 6. Force View to 'assets'
                 // @ts-ignore
                 useAssetStore().changeDirectory('assets');
                 
                 // @ts-ignore
                 if (ui.setLoading) ui.setLoading(false);
            } else {
                console.error('Failed to create project:', result.error);
                // @ts-ignore
                if (ui.setLoading) ui.setLoading(false);
                alert('Failed to create project: ' + result.error);
            }
        }
    }

    static closeProject() {
        projectState.currentProjectPath = null;
        projectState.projectName = 'Untitled';
        if (projectState.watcherCleanup) {
            projectState.watcherCleanup();
            projectState.watcherCleanup = null;
        }
        console.log('[ProjectManager] Project closed');
    }

    static async openProject(customPath?: string) {
        const _pStart = performance.now();
        console.log('ProjectManager: Opening project...', customPath || '(Interactive)');
        const fs = getFileSystem();
        const ui = useUIStore();
        
        const pathOrHandle = customPath || await fs.selectFolder();
        
        if (pathOrHandle) {
            // @ts-ignore
            if (ui.setLoading) ui.setLoading(true, 'Opening Project...');
            try {
                projectState.currentProjectPath = pathOrHandle;
                
                if (typeof pathOrHandle === 'string') {
                    projectState.projectName = pathOrHandle.split(/[/\\]/).pop() || 'Project';
                 } else {
                    projectState.projectName = (pathOrHandle as FileSystemDirectoryHandle).name;
                 }
                
                // Initialize FileSystem Context
                // For WebFS, this sets currentProject so readFile works.
                await fs.openProject(projectState.projectName);

                // 1. Load Manifest
                const { ProjectManifestManager } = await import('./ProjectManifestManager');
                const success = await ProjectManifestManager.loadProject('project.json');

                if (!success) {
                    console.warn('[ProjectManager] project.json not found. Creating default empty.');
                    const { AssetDatabase } = await import('./AssetDatabase');
                    AssetDatabase.instance.hydrate([]);
                }
                
                // 2. Notify AssetStore
                // @ts-ignore
                await useAssetStore().refreshFromDatabase();
                
                const _pEnd = performance.now();
                console.log(`%c ⏱️ LOAD COMPLETE: ${(_pEnd - _pStart).toFixed(2)}ms `, 'background: #00ffff; color: #222; font-size: 20px;');
                
                this.addToRecents(projectState.projectName, typeof pathOrHandle === 'string' ? pathOrHandle : undefined);

                // Load Initial Scene
                const { SceneManager } = await import('../../engine/managers/SceneManager');
                const { ProjectManifestManager: PM } = await import('./ProjectManifestManager');
                const { useProjectSettingsStore } = await import('../../stores/useProjectSettingsStore');

                // SYNC PROJECT LAYERS TO SCENE MANAGER
                // This ensures the SceneManager knows the layer templates before loading the scene,
                // preventing the "Loading scene WITHOUT Templates" warning and duplicates.
                const settingsStore = useProjectSettingsStore();
                if (settingsStore.settings.layers) {
                    SceneManager.setProjectLayers(settingsStore.settings.layers);
                }
                
                const manifest = PM.manifest;
                let sceneLoaded = false;
                
                if (manifest && manifest.scenes && manifest.scenes.length > 0) {
                     // Try loading first scene
                     if (manifest.scenes[0]) {
                        const scenePath = manifest.scenes[0].path;
                        
                        // SAFEQUARD 1: Explicitly Hydrate DB with resources (if missing)
                        const { AssetDatabase } = await import('./AssetDatabase');
                        if (manifest.resources && manifest.resources.length > 0) {
                            // Merge with existing to avoid blowing away watcher updates if they happened
                            manifest.resources.forEach(r => {
                                if (r && r.path) {
                                    AssetDatabase.instance.registerAsset(r.path, r.type as any);
                                } else {
                                    console.warn('[ProjectManager] Skipping invalid resource in manifest:', r);
                                }
                            });
                        } else {
                            AssetDatabase.instance.registerAsset(scenePath, 'scene');
                        }

                        // SAFEQUARD 2: Validate File Existence BEFORE passing to Manager
                        // This helps diagnosis: Is it FS failure or Parse failure?
                        try {
                             // Use raw FS to check existence by attempting to read it
                             await fs.readFile(scenePath);
                             
                             console.log(`[ProjectManager] Verified Scene File exists: ${scenePath}`);
                             sceneLoaded = await SceneManager.loadSceneByPath(scenePath);
                        } catch (fsError) {
                             console.error(`[ProjectManager] CRITICAL: Initial Scene File NOT FOUND or Unreadable: ${scenePath}`, fsError);
                             ui.showToast({ title: 'Scene Missing', description: `Could not read ${scenePath}.`, type: 'error' });
                        }
                     }
                }
                
                if (!sceneLoaded) {
                    console.warn('[ProjectManager] Scene load failed or no scenes. Creating default.');
                    // If we failed to load the expected scene, we should probably ALERT the user rather than silently creating Untitled
                    if (manifest && manifest.scenes && manifest.scenes.length > 0) {
                         ui.showToast({ title: 'Load Error', description: 'Failed to load initial scene. Created "Untitled" fallback.', type: 'warning' });
                    }
                    SceneManager.createDefaultScene();
                }

                // 3. Force View to 'assets' Master Folder
                // @ts-ignore
                useAssetStore().changeDirectory('assets');
                
                // 4. Initialize Watcher
                await this.initProjectWatcher(fs, projectState.currentProjectPath as any);

            } catch (e: any) {
                console.error('[ProjectManager] Failed to open project:', e);
                ui.showToast({ title: 'Open Failed', description: e.message || 'Unknown Error', type: 'error' });
                
                // If it was a pinned/recent path (string), remove it if it failed
                if (typeof pathOrHandle === 'string') {
                    const recents = this.getRecents().filter(r => r.path !== pathOrHandle && r.name !== pathOrHandle);
                    localStorage.setItem('ulikit_recents', JSON.stringify(recents));
                    alert(`Project "${pathOrHandle}" not found. Removed from Recents.`);
                }
                
                // Reset State
                projectState.currentProjectPath = null;
                projectState.projectName = 'Untitled';
                
            } finally {
                // @ts-ignore
                if (ui.setLoading) ui.setLoading(false);
            }
        }
    }

    static async saveProject() {
        console.log('ProjectManager: Saving project...');
        
        // 1. Save Active Scene
        const { SceneManager } = await import('../../engine/managers/SceneManager');
        const json = SceneManager.saveScene();
        const fs = getFileSystem();
        
        if (projectState.currentProjectPath) {
             const scenesDir = 'assets/scenes';
             const filename = `${SceneManager.activeSceneName.replace(/\s+/g, '_')}.json`;
             const fullPath = `${scenesDir}/${filename}`;
             
             await fs.writeFile(fullPath, json);
             console.log(`[ProjectManager] Saved scene to ${fullPath}`);

             // 2. Save Manifest (project.json)
             const { ProjectManifestManager } = await import('./ProjectManifestManager');
             
             // Update Scene in Manifest
             if (ProjectManifestManager.manifest) {
                 if (!ProjectManifestManager.manifest.scenes) {
                     ProjectManifestManager.manifest.scenes = [];
                 }
                 
                 const scenes = ProjectManifestManager.manifest.scenes;
                 const existingIdx = scenes.findIndex(s => s.path === fullPath);
                 
                 if (existingIdx !== -1) {
                    // Determine safer access
                    const existing = scenes[existingIdx];
                    if (existing) {
                        existing.updated = Date.now();
                    }
                 } else {
                     scenes.push({
                         name: SceneManager.activeSceneName,
                         path: fullPath,
                         id: crypto.randomUUID(),
                         updated: Date.now()
                     });
                 }
             }
             
             await ProjectManifestManager.saveProject('project.json');
             
             // EMIT EVENT so UI can refresh (ScenesPanel listener)
             const { eventBus } = await import('../../engine/core/EventBus');
             eventBus.emit('project-saved');

             projectState.isDirty = false;
             alert(`Project Saved.`);
        } else {
            console.warn('[ProjectManager] No project open, cannot save.');
        }
    }
    static async importAssets(inputs: (File | { file: File, path: string })[], targetFolderVal: string = '') {
        console.log('ProjectManager: Importing', inputs.length, 'items to', targetFolderVal);
        const fs = getFileSystem();
        const ui = useUIStore();
        
        // @ts-ignore
        if (ui.setLoading) ui.setLoading(true, `Importing ${inputs.length} files...`, 'determinate');

        try {
            const { AssetDatabase } = await import('./AssetDatabase');
            const { ProjectManifestManager } = await import('./ProjectManifestManager');
            
            let addedCount = 0;
            const total = inputs.length;
            
            for (let i = 0; i < total; i++) {
                const item = inputs[i];
                if (!item) continue;

                // Update Progress
                const percent = ((i) / total) * 100;
                // @ts-ignore
                if (ui.setProgress) ui.setProgress(percent, `Processing ${i+1}/${total}`);

                 // Determine File and Relative Path
                let file: File;
                let relPath: string;

                if ('file' in item && 'path' in item) {
                    file = item.file;
                    relPath = item.path;
                } else {
                    file = item as File;
                    relPath = file.name;
                }

                // Construct full Destination Path (Target Folder + Relative Path from Drop)
                // ENFORCE ASSETS FOLDER: All imports must go into 'assets/'
                let safeTargetFolder = targetFolderVal;
                
                // If target is empty or root, force 'assets'
                if (!safeTargetFolder || safeTargetFolder === '.' || safeTargetFolder === '/') {
                    safeTargetFolder = 'assets';
                }
                // If target doesn't start with assets, prepend it (unless it's empty which we handled)
                else if (!safeTargetFolder.startsWith('assets')) {
                     safeTargetFolder = `assets/${safeTargetFolder}`;
                }

                const fullDestPath = `${safeTargetFolder}/${relPath}`;
                
                // Extract Dir and Filename for importFile
                const lastSlash = fullDestPath.lastIndexOf('/');
                const targetDir = lastSlash > -1 ? fullDestPath.substring(0, lastSlash) : '';
                const fileName = lastSlash > -1 ? fullDestPath.substring(lastSlash + 1) : fullDestPath;

                let success = false;

                // 1. Write to Disk (using importFile to ensure directories are created)
                if (fs.getPathForFile && fs.importFile) {
                    const blobUrl = fs.getPathForFile(file);
                    const result = await fs.importFile(blobUrl, targetDir, fileName);
                    if (!result.success) {
                        console.error(`Failed to import ${fileName}:`, result.error);
                        // Optional: show toast for individual failure? Or checking summary at end?
                        // Just log for now.
                    } else {
                        success = true;
                    }
                } else {
                    success = await fs.writeFile(fullDestPath, file);
                }
                
                if (success) {
                    // 2. Register in Database
                    AssetDatabase.instance.registerAsset(fullDestPath);
                    addedCount++;
                } else {
                    console.warn(`Skipping registration for failed import: ${fullDestPath}`);
                }
            }
            
            // 3. Save Manifest
            if (addedCount > 0) {
                await ProjectManifestManager.saveProject('project.json');
                
                // 4. Update UI
                await useAssetStore().refreshFromDatabase();
                ui.showToast({ title: 'Import Complete', description: `Imported ${addedCount} files.`, type: 'success' });
            }

        } catch (e) {
            console.error('Import failed:', e);
            ui.showToast({ title: 'Import Failed', description: String(e), type: 'error' });
        } finally {
            // @ts-ignore
            if (ui.setLoading) ui.setLoading(false);
        }
    }

    static async deleteAsset(targetPath: string) {
        console.log('ProjectManager: Deleting', targetPath);
        const fs = getFileSystem();
        const ui = useUIStore();
        
        if (targetPath === 'assets') {
             ui.showToast({ title: 'Error', description: 'Cannot delete root assets folder.', type: 'error' });
             return;
        }

        // Blocking UI
        // @ts-ignore
        if (ui.setLoading) ui.setLoading(true, `Deleting ${targetPath}...`, 'indeterminate');

        try {
            const success = await fs.deleteFile(targetPath);
            if (success) {
                 const { AssetDatabase } = await import('./AssetDatabase');
                 const { ProjectManifestManager } = await import('./ProjectManifestManager');
                 
                 // Unregister exact match
                 AssetDatabase.instance.deleteAsset(targetPath);
                 // Cleanup if it was a folder (recursive removal from DB)
                 AssetDatabase.instance.cleanupFolder(targetPath);
    
                 // NEW: Deep Cleanup of Component References in the Active Scene
                 const { SceneManager } = await import('../../engine/managers/SceneManager');
                 SceneManager.removeAssetReferences(targetPath);
                 
                 await ProjectManifestManager.saveProject('project.json');
                 
                 // @ts-ignore
                 await useAssetStore().refreshFromDatabase();
                 ui.showToast({ title: 'Deleted', description: `Deleted ${targetPath}`, type: 'success' });
            } else {
                ui.showToast({ title: 'Error', description: 'Failed to delete file.', type: 'error' });
            }
        } catch (e) {
            console.error('Delete failed:', e);
             ui.showToast({ title: 'Error', description: 'Delete failed.', type: 'error' });
        } finally {
            // @ts-ignore
            if (ui.setLoading) ui.setLoading(false);
        }
    }
    static async createFolder(parentPath: string) {
        const ui = useUIStore();
        
        // Prompt for Name
        const name = await ui.prompt({
            title: 'New Folder',
            message: 'Enter folder name:',
            defaultValue: 'New Folder',
            confirmText: 'Create'
        });
        
        if (!name) return; // Cancelled
        
        // Validation
        if (!/^[a-zA-Z0-9_-]+$/.test(name)) { // Simple validation
             // Maybe allow spaces? Let's allow spaces for now but generally stick to safe chars
        }
        
        // Construct Path
        // If parentPath is 'assets', new path is 'assets/name'
        // If parentPath is empty, force 'assets/name'
        let targetParent = parentPath;
        if (!targetParent || targetParent === '.') targetParent = 'assets';
        
        const fs = getFileSystem();
        const finalPath = `${targetParent}/${name}`;
        
        // Check for Duplicates
        try {
            // We check parent folder contents to avoid 404s/errors from stat'ing non-existent files if FS throws
            const entries = await fs.readdir(targetParent);
            const exists = entries.some(e => e.name === name); // Case sensitive? Win is insensitive.
            
            if (exists) {
                const confirmed = await ui.confirm({
                    title: 'Folder Exists',
                    message: `Folder "${name}" already exists. Do you want to use it?`,
                    confirmText: 'Use/Merge',
                    cancelText: 'Cancel'
                });
                if (!confirmed) return;
            }
        } catch (e) {
            // Parent might create issue, but if parent doesnt exist, we can't create child anyway usually.
            // Ignore error and try to create.
        }

        console.log(`[ProjectManager] Creating folder: ${finalPath}`);
        
        // Actual folder creation logic
        if (fs.createFolder) {
            const success = await fs.createFolder(finalPath);
            if (success) {
                const { AssetDatabase } = await import('./AssetDatabase');
                AssetDatabase.instance.registerAsset(finalPath, 'directory');
                
                const { ProjectManifestManager } = await import('./ProjectManifestManager');
                await ProjectManifestManager.saveProject('project.json'); // Save manifest to reflect new folder
                await useAssetStore().refreshFromDatabase(); // Refresh UI
                ui.showToast({ title: 'Success', description: `Folder "${name}" created.`, type: 'success' });
            } else {
                ui.showToast({ title: 'Error', description: `Failed to create folder "${name}".`, type: 'error' });
            }
        } else {
            console.error('fs.createFolder not implemented');
            ui.showToast({ title: 'Error', description: 'File system does not support folder creation.', type: 'error' });
        }
    }

    static async renameAsset(oldPath: string, newName: string) {
        console.log(`[ProjectManager] Renaming ${oldPath} to ${newName}`);
        const fs = getFileSystem();
        const ui = useUIStore();
        
        // 1. Calculate New Path
        const parts = oldPath.split('/');
        parts.pop(); // Remove old name
        const newPath = [...parts, newName].join('/');
        
        if (oldPath === newPath) return; // No change

        // 2. Validate Existence (TODO: Check if newPath exists)

        // @ts-ignore
        if (ui.setLoading) ui.setLoading(true, 'Renaming...', 'indeterminate');

        try {
            // 3. Move File Logic
            // HACK: Use Node/Electron IPC directly if we can, or add rename to interface.
            // Check if FS has rename
            // @ts-ignore
            if (fs.rename) {
                 // @ts-ignore
                 const success = await fs.rename(oldPath, newPath);
                 if (!success) throw new Error('FS rename failed');
            } else {
                // Fallback for missing rename: Error out for now
                throw new Error('FileSystem does not support rename yet. Please implement fs.rename.');
            }

            // 4. Update Database
            const { AssetDatabase } = await import('./AssetDatabase');
            AssetDatabase.instance.moveAsset(oldPath, newPath);
            
            // 5. Update References in Scene
            const { SceneManager } = await import('../../engine/managers/SceneManager');
            SceneManager.updateAssetReferences(oldPath, newPath);
            
            // 6. Save Manifest
            const { ProjectManifestManager } = await import('./ProjectManifestManager');
            await ProjectManifestManager.saveProject('project.json');
            
            // 7. Refresh UI
            await useAssetStore().refreshFromDatabase();
            ui.showToast({ title: 'Success', description: 'Renamed successfully', type: 'success' });

        } catch (e: any) {
            console.error('Rename failed:', e);
            ui.showToast({ title: 'Error', description: e.message || 'Rename failed', type: 'error' });
        } finally {
            // @ts-ignore
            if (ui.setLoading) ui.setLoading(false);
        }
    }



    private static async initProjectWatcher(fs: any, path: string | FileSystemDirectoryHandle) {
        if (projectState.watcherCleanup) {
            projectState.watcherCleanup();
        }
        
        projectState.watcherCleanup = await fs.watchProject(path, async (event: any) => {
            // console.log('[ProjectManager] Watcher Event:', event);
            const { AssetDatabase } = await import('./AssetDatabase');
            const { ProjectManifestManager } = await import('./ProjectManifestManager');
            
            let needsSave = false;

            if (event.event === 'initial') {
                for (const file of event.files || []) {
                    if (file.type === 'file' && !file.name.endsWith('.meta')) {
                         AssetDatabase.instance.registerAsset(file.path);
                    }
                }
                needsSave = true;
            } else if (event.event === 'add') {
                 if (!event.path.endsWith('.meta')) {
                     AssetDatabase.instance.registerAsset(event.path);
                     needsSave = true;
                 }
            } else if (event.event === 'unlink') {
                // Remove from DB? AssetDatabase needs unregister method?
                // For now, reload DB or strict removal?
                // AssetDatabase.instance.removeAsset(event.path);
            }
            
            if (needsSave) {
                 await ProjectManifestManager.saveProject('project.json');
                 // Refresh UI
                 await useAssetStore().refreshFromDatabase();
            }
        });
    }
}
